---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pangolin-gateway-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: ./k8s/chart
      sourceRef:
        kind: GitRepository
        name: pangolin-gateway-controller
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: "ghcr.io/dxas90/pangolin-gateway-controller"
    env:
      variables:
        VARIABLES_THAT_SHOULD_BE_PRINTED: "LOG_LEVEL EVENT_THRESHOLD NODE_ENV PORT REDIS_DB REDIS_HOST REDIS_PORT STORAGE_DRIVER"
