apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: pangolin
spec:
  controllerName: pangol.in/gateway-controller
  description: "Pangolin Gateway for Kubernetes Gateway API integration"
