{{- if .Values.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "base.priorityClassName" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
value: {{ .Values.priorityClass.value | int }}
globalDefault: {{ .Values.priorityClass.globalDefault }}
{{- with .Values.priorityClass.preemptionPolicy }}
preemptionPolicy: {{ . }}
{{- end }}
description: {{ .Values.priorityClass.description | quote }}
{{- end }}
